package iposSA;

import java.util.List;

/**
 * This class represents a report generated by the system.
 * just a data structure for now
 */
public class Report {

    private String reportType;
    private String generatedDate;
    private double totalValue;
    private List<String> entries;

    /**
     * Default constructor
     */
    public Report() {
    }

    /**
     * Constructor with report type
     */
    public Report(String reportType) {
        this.reportType = reportType;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String getGeneratedDate() {
        return generatedDate;
    }

    public void setGeneratedDate(String generatedDate) {
        this.generatedDate = generatedDate;
    }

    public double getTotalValue() {
        return totalValue;
    }

    public void setTotalValue(double totalValue) {
        this.totalValue = totalValue;
    }

    public List<String> getEntries() {
        return entries;
    }

    public void setEntries(List<String> entries) {
        this.entries = entries;
    }
}